# Generated by Django 4.0.5 on 2022-06-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, verbose_name='RUN')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'No Informa')], default='', max_length=1)),
                ('carrera', models.CharField(choices=[('A', 'Ingeniería en Información y Control de Gestión'), ('B', 'Ingeniería en Prevención de Riesgos y Medioambiente'), ('C', 'Biología Marina'), ('D', 'Ingeniería en Acuicultura'), ('E', 'Ingeniería Comercial'), ('F', 'Derecho'), ('G', 'Ingeniería Civil Industrial'), ('H', 'Pedagogía en Filosofía y Religión'), ('I', 'Pedagogía en Educación Diferencial con Mención en Desarrollo Emocional y Cognitivo'), ('J', 'Enfermería'), ('K', 'Kinesiología'), ('L', 'Medicina'), ('M', 'Nutrición y Dietética'), ('N', 'Ingeniería Civil en Computación e Informática'), ('O', 'Ingeniería en Tecnologías de Información'), ('P', 'Licenciatura en Ciencias Religiosas')], default='A', max_length=1)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('correo2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico Alternativo')),
                ('curso1', models.CharField(blank=True, choices=[('A', 'Aprobado'), ('R', 'Reprobado')], default='', max_length=1, verbose_name='Curso Basico:')),
                ('fecha_curso1', models.CharField(max_length=6, verbose_name='Aprobacion Curso Básico')),
                ('curso2', models.CharField(blank=True, choices=[('A', 'Aprobado'), ('R', 'Reprobado')], default='', max_length=1, verbose_name='Curso Intermedio:')),
                ('fecha_curso2', models.CharField(max_length=6, verbose_name='Aprobacion Curso Intermedio')),
                ('curso3', models.CharField(blank=True, choices=[('A', 'Aprobado'), ('R', 'Reprobado')], default='', max_length=1, verbose_name='Curso Avanzado:')),
                ('fecha_curso3', models.CharField(max_length=6, verbose_name='Aprobacion Curso Avanzado')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'Alumnos',
            },
        ),
    ]
