# Generated by Django 4.0.5 on 2022-06-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electronico Institucional'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_curso1',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Aprobacion Curso Básico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_curso2',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Aprobacion Curso Intermedio'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_curso3',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Aprobacion Curso Avanzado'),
        ),
    ]
