# Generated by Django 4.0.5 on 2022-06-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_alumnos', '0002_alter_alumno_correo_alter_alumno_fecha_curso1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('departamento', models.CharField(choices=[('A', 'CIMET'), ('B', 'Exelencia Academica')], default='A', max_length=1)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico Institucional')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'Funcionarios',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_alumnos.funcionario', verbose_name='Funcionario'),
        ),
    ]
