# Generated by Django 4.0.5 on 2022-06-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_alumnos', '0004_alter_alumno_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_alumnos.funcionario', verbose_name='Funcionario'),
        ),
    ]
