# Generated by Django 4.0.5 on 2022-06-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_alumnos', '0006_f_avanzada_f_especializada_f_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_especializada',
            name='semestre',
            field=models.CharField(choices=[('10', '10'), ('20', '20')], default='', max_length=2, verbose_name='Semestre de aprobación'),
        ),
    ]
