# Generated by Django 4.0.5 on 2022-06-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_alumnos', '0007_alter_f_especializada_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_avanzada',
            name='semestre',
            field=models.CharField(choices=[('10', '10'), ('20', '20')], default='', max_length=2, verbose_name='Semestre de aprobación'),
        ),
        migrations.AlterField(
            model_name='f_inicial',
            name='semestre',
            field=models.CharField(choices=[('10', '10'), ('20', '20')], default='', max_length=2, verbose_name='Semestre de aprobación'),
        ),
    ]
