# Generated by Django 4.0.5 on 2022-06-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_alumnos', '0010_alter_funcionario_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo Electronico Institucional'),
        ),
    ]
